[package]
name = "s3s-codegen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
codegen-writer = "0.2.0"
heck = "0.4.1"
nugine-rust-utils = "0.3.1"
numeric_cast = "0.2.1"
regex = "1.9.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = { version = "1.0.103", features = ["preserve_order"] }
serde_urlencoded = "0.7.1"
